include: security_sales_1-1.0-0.4.yaml
task: security_sales_1-1.0-0.5
description: "ユーザー: 与えられた選択肢の中から、最適な答えを選んでください。\nシステム: 分かりました。\n\n"
fewshot_delimiter: "\n"
doc_to_text: !function utils.doc_to_text_05
