# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test API runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --dev
    - name: Run API test
      run: |
        cat << EOF > .env
        OPENAI_API_BASE=https://api.platform.preferredai.jp/
        OPENAI_API_KEY=$(echo ${{ secrets.PLAMO_API_KEY }})
        EOF
        export TASK="cma_basics,cpa_audit,security_sales_1,fp2"
        yes | uv run python api_models.py --model self-hosted-chat-1 --model_args model=plamo-2.1-prime --tasks $TASK --num_fewshot 0 --output_path "models/plamo/plamo-2.1-prime/result-default.json"
