# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test HF runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --dev
    - name: Run HF test
      run: |
        yes | uv run python main.py --model hf --device cpu \
          --model_args "pretrained=kanhatakeyama/0405_100m_clean_ja,trust_remote_code=True,dtype=float32" \
          --tasks "chabsa,cma_basics,cpa_audit,fp2,security_sales_1" --num_fewshot 0 --limit 100 \
          --output_path "models/kanhatakeyama/0405_100m_clean_ja/result-default.json"
